<a href="https://colab.research.google.com/github/Kavya-kakkar/American-Express-Data-Analysis/blob/main/Data_Preprocessing_Template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing

## Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Importing Dataset

In [ ]:
data_set = pd.read_csv('american.csv')
X = data_set.iloc[: , 0:-1].values
y = data_set.iloc[: , -1].values

In [ ]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [ ]:
print(y)

[0 0 0 ... 0 1 0]





## Handling Missing Data

## Encoding Categorical Data

Gender Column : Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[: , 2] = label_encoder.fit_transform(X[:, 2])

In [ ]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


**Geography Column : One hot Encoding**

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])] , remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting data into Test set & Training Set


In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size = 0.2 ,random_state = 0)
print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[1.0 0.0 0.0 ... 4 1 264201]
 [0.0 0.0 1.0 ... 4 1 328575]
 [1.0 0.0 0.0 ... 2 0 168958]
 ...
 [0.0 0.0 1.0 ... 2 1 248115]
 [0.0 0.0 1.0 ... 2 1 499155]
 [1.0 0.0 0.0 ... 2 0 10454]]
[[0.0 0.0 1.0 ... 2 1 502959]
 [0.0 0.0 1.0 ... 4 1 80970]
 [1.0 0.0 0.0 ... 4 1 2568]
 ...
 [1.0 0.0 0.0 ... 4 0 294987]
 [1.0 0.0 0.0 ... 2 0 180942]
 [1.0 0.0 0.0 ... 2 1 538471]]
[0 0 0 ... 1 1 0]
[1 0 0 ... 1 0 1]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

[[ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857  0.65086753
  -0.06854301]
 [-1.00568294 -0.57109746  1.72639831 ...  0.90580857  0.65086753
   0.34018176]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -0.67326188]
 ...
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
  -0.17067658]
 [-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
   1.4232319 ]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -1.67963883]]
[[-1.00568294 -0.57109746  1.72639831 ... -0.951175    0.65086753
   1.44738434]
 [-1.00568294 -0.57109746  1.72639831 ...  0.90580857  0.65086753
  -1.23191715]
 [ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857  0.65086753
  -1.72970878]
 ...
 [ 0.99434917 -0.57109746 -0.5792406  ...  0.90580857 -1.53641095
   0.12692412]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175   -1.53641095
  -0.59717281]
 [ 0.99434917 -0.57109746 -0.5792406  ... -0.951175    0.65086753
   1.67285788]]


ANN

Intialization

In [ ]:
ann = tf.keras.Sequential()

Adding input layer and first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6 , activation = 'relu'))

Adding second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 6 ,activation = 'relu'))

Adding output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units = 1 ,activation = 'sigmoid'))

**ANN TRAINING**

ANN compiling

In [ ]:
ann.compile(optimizer = 'adam' , loss = 'binary_crossentropy' , metrics = ['accuracy'] )

Training on training dataset

In [ ]:
ann.fit(X_train , y_train , batch_size=32 , epochs=120)

Epoch 1/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8489 - loss: 0.3582
Epoch 2/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8503 - loss: 0.3536
Epoch 3/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8502 - loss: 0.3601
Epoch 4/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8442 - loss: 0.3671
Epoch 5/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8503 - loss: 0.3532
Epoch 6/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8554 - loss: 0.3467
Epoch 7/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8593 - loss: 0.3359
Epoch 8/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8544 - loss: 0.3490
Epoch 9/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8628 - loss: 0.3322
Epoch 10/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8478 - loss: 0.3542
Epoch 11/120
249/249 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8568 - loss: 0.3534
Epoch 12/120
249/249 ━━━━━━━━━━━━━━━━━━━━

**Predictions**

Single Prediction

In [ ]:
print(ann.predict(sc.transform([[0.0 , 1.0 , 0.0 , 0.0 , 501 , 0 , 32 , 2 , 0.0 , 4 , 545501]])) > 0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
[[ True]]


Prediction on testset

In [ ]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)),1))

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 888us/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


Confusion matrix

In [ ]:
from sklearn.metrics import confusion_matrix  , accuracy_score
cm = confusion_matrix(y_test , y_pred)
print(cm)
accuracy_score(y_test , y_pred)


[[1511   62]
 [ 219  194]]


0.8585095669687814